# Generated by Django 5.0.2 on 2024-03-11 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_date_created', models.DateField()),
                ('election_closing_date', models.DateField()),
                ('election_is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electoral_position_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_first_name', models.CharField(max_length=100)),
                ('member_lastname', models.CharField(max_length=100)),
                ('member_date_of_birth', models.DateField()),
                ('member_contact', models.CharField(max_length=15)),
                ('member_address', models.CharField(max_length=100)),
                ('member_rank', models.IntegerField()),
                ('member_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.campus')),
                ('member_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_member_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.election')),
                ('election_member_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.member')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_election_member_number_votes', models.IntegerField(default=0, null=True)),
                ('member_avatar', models.ImageField(upload_to='uploads/')),
                ('candidate_election_election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.election')),
                ('candidate_election_electoral_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.electoralposition')),
                ('candidate_election_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.member')),
                ('candidate_election_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.party')),
            ],
        ),
    ]
