# Generated by Django 5.0.2 on 2024-02-22 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_first_name', models.CharField(max_length=100)),
                ('member_lastname', models.CharField(max_length=100)),
                ('member_date_of_birth', models.DateField()),
                ('member_contact', models.CharField(max_length=15)),
                ('member_address', models.CharField(max_length=100)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.course')),
            ],
        ),
    ]
